httpHeaderAdd: eliminate warning about writing into buffer of wrong size
The code in httpHeaderLinkAdd() tries to write an URL plus the
LINK_REL_AND_TYPE into a buffer, plus some characters:

sprintf(linkP, "<%s>; %s", url, LINK_REL_AND_TYPE);

There is a buffer on the stack with 256 bytes; if the size of the url plus the
size of LINK_REL_AND_TYPE plus the surrounding characters are larger than this
buffer's size, a new buffer is allocated using malloc().

However, the check for the size calculates incorrectly, and thus GCC throws
this warning:

src/lib/rest/httpHeaderAdd.cpp:106:20: error: '%s' directive writing up to 331 bytes into a region of size 255 [-Werror=format-overflow=]
  106 |   sprintf(linkP, "<%s>; %s", url, LINK_REL_AND_TYPE);
      |                    ^~

Fix the calculation.