httpHeaderAdd.cpp: make sure we don't sprintf() more than INT_MAX characters
sprintf() returns the number of characters it has written, so we must make sure
the argument of sprintf is not larger than INT_MAX.

Avoid this warning (turned into an error by -Werror):

src/lib/rest/httpHeaderAdd.cpp:106:22: error: '>; ' directive output between 3 and 3 bytes may cause result to exceed 'INT_MAX' [-Werror=format-overflow=]
  106 |   sprintf(linkP, "<%s>; %s", url, LINK_REL_AND_TYPE);
      |                      ^~~