OrionLdRestService.h: define constants with correct type
On x86_64, unsigned long is 64 bit; however, this might not be the case on
other architectures. For example, on ARM32, unsigned long is 32 bit and we get
this warning (that turns into an error with -Wall):

src/lib/orionld/rest/OrionLdRestService.h:151:52: error: left shift count >= width of type [-Werror=shift-count-overflow]
  151 | #define ORIONLD_URIPARAM_OBSERVEDAT           (1UL << 33)
      |                                                ~~~~^~~~~

Use the stdint.h integer constant UNIT64_C() to convert to a type of at least
64 bit.